# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 8888:5432
  frontend:
    build: .
    ports: 
      - 80:80
  backend:
    build: 
        context: backend
        args: 
            IPADDR: ${IPADDR}
    ports: 
      - 3000:3000
