# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    build: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  frontend:
    build: .
    ports: 
      - 4200:80
  backend:
    build: backend
    environment: 
      IPADDR: ${IPADDR}
      DBADDR: postgres
    ports: 
      - 3000:3000
      - 3333:3333
